name: daily-crawl

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  # <--- 이 줄이 있어야 버튼이 생깁니다!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Run Crawler
        run: |
          python main.py
